my_age = 19 #int
my_height = 163.4 #float
my_dogs_name = "Badem" #str
item_list = ['food',15,'job',75.6] #list
information = {"name": "ada", "age": "19"} #dict
tuple1 = (10,"hello",200.3) #tup
set1 = ("a","b") #set
is_active = True
empty = None